# Generated by Django 3.1.7 on 2021-03-27 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=50)),
                ('WalkedAway', models.BooleanField(null=True)),
                ('Kickedout', models.BooleanField()),
                ('Served', models.BooleanField()),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('GuestNumber', models.PositiveSmallIntegerField()),
                ('beginOfServiceTime', models.DateTimeField(blank=True)),
                ('endOfServiceTime', models.DateTimeField(blank=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.category')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.director')),
                ('Queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.queue')),
                ('Queueoperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.queueoperator')),
            ],
        ),
    ]
