# Generated by Django 3.1.7 on 2021-03-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='password',
        ),
    ]
