# Generated by Django 3.1.6 on 2021-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('ContactFirstName', models.CharField(max_length=45)),
                ('ContactLastName', models.CharField(max_length=45)),
                ('EmailAddress', models.EmailField(max_length=250)),
                ('PhoneNumber', models.CharField(max_length=45)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
