# Generated by Django 3.1.6 on 2021-03-04 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('EmailAddress', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField()),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.director')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactFirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ContactLastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Queueoperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('EmailAddress', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('Director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.director')),
                ('Queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.queue')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('CreatedAt', models.DateTimeField(auto_now=True)),
                ('Queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.queue')),
            ],
        ),
    ]
