# Generated by Django 3.1.7 on 2021-03-14 23:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210304_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='queue_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
