# Generated by Django 3.1.7 on 2021-03-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_queue_queue_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='QRcode',
            field=models.ImageField(null=True, upload_to='QRcodes/'),
        ),
    ]
