# Generated by Django 3.1.7 on 2021-03-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_queue_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='QRcodes/'),
        ),
    ]
