# Generated by Django 3.1.7 on 2021-03-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210315_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueoperator',
            name='Queue',
        ),
        migrations.AddField(
            model_name='queueoperator',
            name='Queue',
            field=models.ManyToManyField(to='customer.Queue'),
        ),
    ]
