# Generated by Django 3.1.7 on 2021-03-20 21:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210319_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='QRcode',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='queue_uuid',
        ),
        migrations.AddField(
            model_name='director',
            name='QRcode',
            field=models.ImageField(blank=True, null=True, upload_to='QRcodes/'),
        ),
        migrations.AddField(
            model_name='director',
            name='director_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
